// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ServerML.Model
{
    public class ModelInput
    {
        [ColumnName("Temperature"), LoadColumn(0)]
        public float Temperature { get; set; }


        [ColumnName("Humidity"), LoadColumn(1)]
        public float Humidity { get; set; }


        [ColumnName("Pulse"), LoadColumn(2)]
        public float Pulse { get; set; }


        [ColumnName("Sp02"), LoadColumn(3)]
        public float Sp02 { get; set; }


        [ColumnName("Disease"), LoadColumn(4)]
        public string Disease { get; set; }


    }
}
